# Generated by Django 5.1.2 on 2025-02-12 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='designers_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=90)),
                ('Place', models.CharField(max_length=100)),
                ('Post', models.CharField(max_length=100)),
                ('Pin', models.IntegerField()),
                ('Phone', models.BigIntegerField()),
                ('Email', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=100)),
                ('Certificate', models.FileField(upload_to='')),
                ('Photo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=90)),
                ('type', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='designs_tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dressname', models.CharField(max_length=100)),
                ('gendertype', models.CharField(max_length=100)),
                ('dresstype', models.CharField(max_length=100)),
                ('design', models.FileField(upload_to='')),
                ('discription', models.TextField()),
                ('season', models.CharField(blank=True, max_length=100, null=True)),
                ('DESIGNER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royaloutfit.designers_table')),
            ],
        ),
        migrations.AddField(
            model_name='designers_table',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royaloutfit.login_table'),
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('date', models.DateField()),
                ('fromid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fid', to='royaloutfit.login_table')),
                ('toid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tid', to='royaloutfit.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='MoreDesignTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_more', models.FileField(upload_to='')),
                ('DESIGN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royaloutfit.designs_tables')),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=90)),
                ('Place', models.CharField(max_length=100)),
                ('Post', models.CharField(max_length=100)),
                ('Pin', models.IntegerField()),
                ('Phone', models.BigIntegerField()),
                ('Email', models.CharField(max_length=100)),
                ('Photo', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royaloutfit.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='rating_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reviews', models.TextField()),
                ('rating', models.FloatField()),
                ('Date', models.DateField()),
                ('DESIGN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royaloutfit.designs_tables')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royaloutfit.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='custom_desgin_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('design_details', models.TextField()),
                ('DESIGNER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royaloutfit.designers_table')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royaloutfit.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='complaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField()),
                ('Date', models.DateField()),
                ('reply', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royaloutfit.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='WardrobeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dress', models.FileField(upload_to='')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dress_type', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royaloutfit.user_table')),
            ],
        ),
    ]
