# Generated by Django 5.1.2 on 2025-02-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royaloutfit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardrobetable',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wardrobetable',
            name='gendertype',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
