# Generated by Django 5.1.2 on 2025-02-05 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royaloutfit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WardrobeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dress', models.FileField(upload_to='')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dress_type', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royaloutfit.user_table')),
            ],
        ),
    ]
