# Generated by Django 5.1.2 on 2025-02-22 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royaloutfit', '0002_wardrobetable_name_wardrobetable_gendertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestImageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='test/')),
                ('date', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('USERID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='royaloutfit.user_table')),
            ],
        ),
    ]
