# Generated by Django 5.1.2 on 2025-02-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royaloutfit', '0002_wardrobetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='designs_tables',
            name='season',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wardrobetable',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
