# Generated by Django 5.1.2 on 2025-03-10 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royaloutfit', '0003_testimagetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_table',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='rating_table1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reviews', models.TextField()),
                ('rating', models.FloatField()),
                ('Date', models.DateField(auto_now_add=True)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royaloutfit.user_table')),
            ],
        ),
    ]
