# Generated by Django 5.1.2 on 2025-02-05 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('royaloutfit', '0003_designs_tables_season_alter_wardrobetable_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designers_table',
            name='Certificate',
        ),
        migrations.RemoveField(
            model_name='designers_table',
            name='Experience',
        ),
    ]
