# Generated by Django 5.1.2 on 2025-03-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royaloutfit', '0004_alter_complaint_table_date_rating_table1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating_table1',
            name='Reviews',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
