# Generated by Django 5.1.2 on 2025-02-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royaloutfit', '0004_remove_designers_table_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designers_table',
            name='Certificate',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designers_table',
            name='Experience',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designers_table',
            name='Photo',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
