# Generated by Django 5.1.2 on 2025-03-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royaloutfit', '0005_alter_rating_table1_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='designs_tables',
            name='platform',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
