# Generated by Django 5.1.2 on 2025-03-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royaloutfit', '0006_designs_tables_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='designs1_tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dressname', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('design', models.FileField(upload_to='')),
            ],
        ),
    ]
